### ISSUE TITLE
Add a token to prevent hijacking from funny users

### ISSUE THREAD

**Issue by joac** [edvm/pysenteishon#14]
Add a token, to be shown on server start and requested on the app to "pair" the phone with the application

**Comment by joac** [comment]
@edvm assign this to me ;)

**Comment by edvm** [comment]
all yours @joac (please branch from develop, you have push permissions) , thanks!

**Comment by edvm** [comment]
@pardo implemented basic auth that can be used when running pysenteishon from command line. 5d1d1fe6

**Comment by pardo** [comment]
👍
