### ISSUE TITLE
Faster way to get the QR code

### ISSUE THREAD

**Issue by humitos** [edvm/pysenteishon#16]
I don't want to open the web browser and click on the menu and that to get the QR. Yes, I'm lazy.

So, I want to show the QR code immediately I run `pysenteishon`. I found a way to do this by showing the QR code on the same terminal in ASCII:

http://pythonhosted.org/PyQRCode/rendering.html#terminal-rendering

Anyway, if it doesn't fit to you, I prefer to generate the Image and open it from Python so I can scan in a very easy way the QR code and get connected to pysenteishon.

I'm looking for approbation before start coding and sending the PR.

**Comment by humitos** [comment]
```
>>> import pyqrcode
>>> text = pyqrcode.create('http://argentinaenpython.com.ar/')
>>> print(text.terminal())
```

**Comment by humitos** [comment]
![screenshot - 161115 - 11 29 18](https://cloud.githubusercontent.com/assets/244656/11187693/59dbb7b8-8c55-11e5-82bb-077a194c4fde.png)

**Comment by edvm** [comment]
It looks really good @humitos , you have the approval :P. Please take in mind if it runs on Windows (if not, no problem, only have consideration to enable this feature when running under Gnu/Linux).
Thank you!

**Comment by erickgnavar** [comment]
Another way could be open a static page with the generated QR code with `webbrowser.open`
