### ISSUE TITLE
La simulacion de teclas no funciona en OSX 10.9.2

### ISSUE THREAD

**Issue by jcarizza** [edvm/pysenteishon#5]

**Comment by humitos** [comment]
@jcarizza ¿qué sucede? ¿tenés forma de compartirnos un ejemplo que no te ande?

Personalmente uso Linux, pero quizás te puedo ayudar a debuggear el problema.

**Comment by erickgnavar** [comment]
Tampoco me funciona en OSX 😢
Buscando en la red, para que se ejecute sin problemas se debe instalar `pyobjc-framework-Quartz` pero el detalle es que las teclas de las flechas no están implementadas en `PyUserInput` como se puede ver [aquí](https://github.com/SavinaRoja/PyUserInput/blob/master/pykeyboard/mac.py#L23), se podría usar usar las teclas `space` y `delete` para avanzar y retroceder slides, no he encontrado equivalentes para arriba y abajo.

Otro detalle es que no me funcionan los botones desde iOS 😢

**Comment by edvm** [comment]
Erick Navarro, gracias por el feedback!
Podrías explicarme que significa que no funcionan los botones?
Respecto de las flechas, efectivamente no están implementadas, hay que
encontrar los códigos '0x',
aunque es buena idea el de utilizar space y delete.
Muchas gracias!

El 3 de mayo de 2016, 23:38, Erick Navarro <notifications@github.com>
escribió:

> Tampoco me funciona en OSX 😢
> Buscando en la red, para que se ejecute sin problemas se debe instalar
> pyobjc-framework-Quartz pero el detalle es que las teclas de las flechas
> no están implementadas en PyUserInput como se puede ver aquí
> <https://github.com/SavinaRoja/PyUserInput/blob/master/pykeyboard/mac.py#L23>,
> se podría usar usar las teclas space y delete para avanzar y retroceder
> slides, no he encontrado equivalentes para arriba y abajo.
>
> Otro detalle es que no me funcionan los botones desde iOS 😢
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/edvm/pysenteishon/issues/5#issuecomment-216726801>
>



-- 
Find me at http://edvm.chiba.ga <https://github.com/edvm>

<edvm@python.org.ar>

**Comment by erickgnavar** [comment]
A lo que me refería es que cuando entro a la página web de pysenteishon desde iOS cuando "presiono" en los botones de las flechas no llega ningún request al servidor, probe desde Android y si funciona.

**Comment by humitos** [comment]
@erickgnavar finalmente encontramos que era un problema en el browser de iOS con respecto a las notificaciones HTML5. Además, como las notificaciones tampoco funcionaban bien en Firefox, Chrome, etc, decidimos quitarlas.

Ahora, en la rama master el código que está funciona en iOS, Android, MacOS, Linux y Windows :)

Pronto voy a liberar la versión 1.0.0 en pypi para que pueda ser instalado con pip.
