### ISSUE TITLE
El browser se abre en http://0.0.0.0:5000/

### ISSUE THREAD

**Issue by humitos** [edvm/pysenteishon#8]
El browser se abre en la dirección incorrecta al correr `pysenteishon`.

Debería abrir en http://localhost:5000/

* Linux: Xubuntu 14.04 LTS
* Python: 3.4.0
* Version pysenteishon: git master

**Comment by edvm** [comment]
Fixed on https://github.com/edvm/pysenteishon/commit/abd174d68b988669188cd0a56dc5b4602db901f9 , now we dont open the web browser anymore. The urls available to connect from the smartphone to the webserver (pysenteishon) are being showed at the console when running pysenteishon, for example:
```
(pysenteishon)[edvm@mitsuki src (develop)]$ python app.py -p 1234
Pysenteishon is running on 0.0.0.0:1234
If you use a firewall, keep in mind to allow connections on port: 1234
On your smartphone, open the web browser using one of the following urls:
	- http://192.168.1.108:1234
```
Thanks!
