### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by humitos** [edvm/pysenteishon#9]
Instalado en py 2.7.6 da un 500 al acceder a la web:

```
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
```

* Linux Xubuntu 14.04 LTS
* Python: 2.7.6
* Version: git master

**Comment by edvm** [comment]
Humitos, gracias por el issue! te agradeceria por favor si podes
levantar pysenteishon desde el shell y copiar/pegar el posible traceback
que hay en al consola?
Muchas gracias!

2015-06-02 10:29 GMT-03:00 Manuel Kaufmann <notifications@github.com>:

> Instalado en py 2.7.6 da un 500 al acceder a la web:
>
> Internal Server Error
>
> The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.
>
>
>    - Linux Xubuntu 14.04 LTS
>    - Python: 2.7.6
>    - Version: git master
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/edvm/pysenteishon/issues/9>.
>



-- 
Broken code @ https://github.com/edvm

<edvm@python.org.ar>

**Comment by humitos** [comment]
No hay traceback ni tampoco encontré una opción "-v" o similar:

```
(tmp-1fe910d2220926e9)[10:53] humitos: tmp-1fe910d2220926e9> pysenteishon 
 * Opening web browser at http://0.0.0.0:5000, please wait ...
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [02/Jun/2015 10:53:31] "GET / HTTP/1.1" 500 -
```

**Comment by edvm** [comment]
Fixeado por @diegoduncan21 en: https://github.com/edvm/pysenteishon/commit/2b99d55e1d8eb80182a8cc551ee1acf8e5471b6a
Gracias! :+1:
